apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auxiliary.name" . }}
  labels:
    app: {{ include "auxiliary.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "auxiliary.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "auxiliary.name" . }}
    spec:
      containers:
        - name: auxiliary
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AWS_REGION
              value: "{{ .Values.env.AWS_REGION }}"
            - name: AUX_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "auxiliary.fullname" . }}-config
                  key: AUX_VERSION
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always

