apiVersion: apps/v1
kind: Deployment
metadata:
  name: auxiliary-auxiliary
  labels:
    app: auxiliary-auxiliary
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auxiliary-auxiliary
  template:
    metadata:
      labels:
        app: auxiliary-auxiliary
    spec:
      containers:
        - name: auxiliary
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION }}
      restartPolicy: Always

