apiVersion: v1
kind: Service
metadata:
  name: auxiliary-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: auxiliary-auxiliary
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

