apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<YOUR_GITHUB_USERNAME>/<YOUR_REPO>.git'
    targetRevision: HEAD
    path: kubernetes/api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: main-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

