replicaCount: 1

image:
  repository: IMAGE_AUX                # replace with your registry/repo e.g. 123456789012.dkr.ecr.eu-west-3.amazonaws.com/auxiliary
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  host: aux.local
  path: /

resources: {}

env:
  AWS_REGION: "eu-west-3"

versions:
  auxiliary: "0.1.0"

