# auxiliary/values.yaml
replicaCount: 1

image:
  repository: 231838751459.dkr.ecr.us-east-1.amazonaws.com/auxiliary-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  AWS_REGION: "us-east-1"

