replicaCount: 1

image:
  repository: 231838751459.dkr.ecr.us-east-1.amazonaws.com/auxiliary-service
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  host: aux.local
  path: /

resources: {}

env:
  AWS_REGION: "eu-west-3"

versions:
  auxiliary: "0.1.0"

