apiVersion: v2
name: monitoring
description: Helm chart pour Prometheus et Grafana
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: prometheus
    version: "45.0.0" # ou la dernière version compatible
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: grafana
    version: "6.17.4" # ou la dernière version compatible
    repository: "https://grafana.github.io/helm-charts"

