apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api-main-api
  labels:
    app: main-api-main-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: main-api-main-api
  template:
    metadata:
      labels:
        app: main-api-main-api
    spec:
      containers:
        - name: main-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION }}
            - name: AUX_URL
              value: {{ .Values.env.AUX_URL }}
      restartPolicy: Always

