apiVersion: v1
kind: Service
metadata:
  name: main-api-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: main-api-main-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

