apiVersion: v1
kind: Service
metadata:
  name: main-api-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "main-api.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

