replicaCount: 1

image:
  repository: main-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  AWS_REGION: "us-east-1"
  AUX_URL: "http://auxiliary-svc.auxiliary.svc.cluster.local:8080"

