# api/values.yaml
replicaCount: 1

image:
  repository: 231838751459.dkr.ecr.us-east-1.amazonaws.com/main-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

env:
  AWS_REGION: "us-east-1"
  AUX_URL: "http://auxiliary-svc.auxiliary.svc.cluster.local:8082"

