replicaCount: 1

image:
  repository: 231838751459.dkr.ecr.us-east-1.amazonaws.com/main-api
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  host: api.local
  path: /

resources: {}

env:
  AWS_REGION: "eu-west-3"
  AUX_URL: "http://auxiliary-svc.auxiliary.svc.cluster.local:8080" # default cluster DNS
  SSM_PARAMETER_PREFIX: "/myapp"

versions:
  main: "0.1.0"
  auxiliary: "0.1.0"

